export const SET_THEME = 'SETH_THEME'
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
// MODEL ACTIONS
export const SET_MODELS = 'SET_MODELS';
export const UPDATE_MODEL_PAID = 'UPDATE_MODEL_PAID';
export const ADD_MODEL = 'ADD_MODEL';
// CLIENT INVOICE ACTIONS
export const ADD_TO_CLIENT_INVOICE = 'ADD_TO_CLIENT_INVOICE';
export const REMOVE_FROM_CLIENT_INVOICE = 'REMOVE_FROM_CLIENT_INVOICE';
export const CLEAR_CLIENT_INVOICE = 'CLEAR_CLIENT_INVOICE';
// FREELANCER INVOICE ACTIONS
export const ADD_TO_FREELANCER_INVOICE = 'ADD_TO_FREELANCER_INVOICE';
export const REMOVE_FROM_FREELANCER_INVOICE = 'REMOVE_FROM_FREELANCER_INVOICE';
export const CLEAR_FREELANCER_INVOICE = 'CLEAR_FREELANCER_INVOICE';
// PRICING ACTIONS
export const UPDATE_CLIENT_PRICE = 'UPDATE_CLIENT_PRICE';
export const UPDATE_FREELANCER_PRICE = 'UPDATE_FREELANCER_PRICE';
export const ADD_CLIENT_ROW = 'ADD_CLIENT_ROW';
export const DELETE_CLIENT_ROW = 'DELETE_CLIENT_ROW';
export const ADD_FREELANCER_ROW = 'ADD_FREELANCER_ROW';
export const DELETE_FREELANCER_ROW = 'DELETE_FREELANCER_ROW';
// INVOICE ACTIONS 
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const UPDATE_INVOICE_PAID = 'UPDATE_INVOICE_PAID';
export const ADD_MODEL_TO_INVOICE = 'ADD_MODEL_TO_INVOICE';
export const REMOVE_MODEL_FROM_INVOICE = 'REMOVE_MODEL_FROM_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';