export const SET_THEME = 'SETH_THEME'
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
// MODEL ACTIONS
export const SET_MODELS = 'SET_MODELS';
export const UPDATE_MODEL_PAID = 'UPDATE_MODEL_PAID';
// CLIENT INVOICE ACTIONS
export const ADD_TO_CLIENT_INVOICE = 'ADD_TO_CLIENT_INVOICE';
export const REMOVE_FROM_CLIENT_INVOICE = 'REMOVE_FROM_CLIENT_INVOICE';
export const CLEAR_CLIENT_INVOICE = 'CLEAR_CLIENT_INVOICE';
// FREELANCER INVOICE ACTIONS
export const ADD_TO_FREELANCER_INVOICE = 'ADD_TO_FREELANCER_INVOICE';
export const REMOVE_FROM_FREELANCER_INVOICE = 'REMOVE_FROM_FREELANCER_INVOICE';
export const CLEAR_FREELANCER_INVOICE = 'CLEAR_FREELANCER_INVOICE';
// PRICING ACTIONS
export const UPDATE_CLIENT_PRICE = 'UPDATE_CLIENT_PRICE';
export const UPDATE_FREELANCER_PRICE = 'UPDATE_FREELANCER_PRICE';